apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
#  local:
#    push: false
  googleCloudBuild:
    projectId: plucky-order-286913
  artifacts:
    - image: us.gcr.io/plucky-order-286913/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .